import SwiftUI
import TranscriberCore

/// What Claude proposed, before any of it is written down.
///
/// A read-before-write step rather than a progress bar that ends with forty
/// new rows in the notes. The model is summarising Taglish it may have
/// misheard, from a transcript that already has its own error rate, so the
/// person who was in the room is the last gate.
struct MinutesSheet: View {
    @Environment(AppState.self) private var state
    @Environment(\.dismiss) private var dismiss

    let review: AppState.MinutesReview
    /// Whether the recording already has a summary that Insert would replace.
    let replacesSummary: Bool

    private var draft: Minutes.Draft { review.draft }

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            header
            Divider()
            ScrollView {
                VStack(alignment: .leading, spacing: 18) {
                    if draft.uncitedCount > 0 { uncitedWarning }
                    if !draft.summary.isEmpty { summary }
                    ForEach(MeetingItemKind.allCases) { kind in
                        let items = draft.items.filter { $0.kind == kind }
                        if !items.isEmpty { section(kind, items) }
                    }
                }
                .padding(16)
            }
            Divider()
            footer
        }
        .frame(width: 620, height: 560)
    }

    private var header: some View {
        VStack(alignment: .leading, spacing: 3) {
            Text("Review minutes").font(.headline)
            Text("\(draft.items.count) item\(draft.items.count == 1 ? "" : "s") proposed. "
                 + "Nothing is saved until you insert them.")
                .font(.caption)
                .foregroundStyle(.secondary)
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .padding(16)
    }

    private var uncitedWarning: some View {
        Label {
            Text("\(draft.uncitedCount) item\(draft.uncitedCount == 1 ? "" : "s") cited a "
                 + "moment that is not in the transcript. Those were kept but have no "
                 + "source link — read them closely.")
        } icon: {
            Image(systemName: "exclamationmark.triangle")
        }
        .font(.caption)
        .foregroundStyle(.orange)
        .padding(10)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(RoundedRectangle(cornerRadius: 6).fill(.orange.opacity(0.1)))
    }

    private var summary: some View {
        VStack(alignment: .leading, spacing: 7) {
            Text(replacesSummary ? "SUMMARY — REPLACES THE CURRENT ONE" : "SUMMARY")
                .font(.caption.weight(.semibold))
                .foregroundStyle(replacesSummary ? .orange : .secondary)
            Text(draft.summary).font(.callout).textSelection(.enabled)
        }
    }

    private func section(_ kind: MeetingItemKind, _ items: [MeetingItem]) -> some View {
        VStack(alignment: .leading, spacing: 7) {
            Label {
                Text(kind.plural.uppercased())
                    .font(.caption.weight(.semibold))
                    .foregroundStyle(.secondary)
            } icon: {
                Image(systemName: kind.symbol).font(.caption)
            }
            ForEach(items) { item in
                HStack(alignment: .firstTextBaseline, spacing: 8) {
                    Text("•").foregroundStyle(.tertiary)
                    Text(item.text).font(.callout).textSelection(.enabled)
                    Spacer(minLength: 8)
                    if let owner = item.owner, !owner.isEmpty {
                        Text(owner).font(.caption).foregroundStyle(.secondary)
                    }
                    if let ms = item.sourceMs {
                        Text(TimeFormat.short(ms: ms))
                            .font(.caption.monospacedDigit())
                            .foregroundStyle(.tertiary)
                    } else {
                        Image(systemName: "questionmark.circle")
                            .font(.caption)
                            .foregroundStyle(.orange)
                            .help("No source in the transcript")
                    }
                }
            }
        }
    }

    private var footer: some View {
        HStack {
            Text("Generated by Claude from the transcript.")
                .font(.caption)
                .foregroundStyle(.secondary)
            Spacer()
            Button("Cancel", role: .cancel) {
                state.minutesDraft = nil
                dismiss()
            }
            .keyboardShortcut(.cancelAction)
            Button("Insert") {
                state.applyMinutes(review)
                dismiss()
            }
            .keyboardShortcut(.defaultAction)
        }
        .padding(16)
    }
}
